package org.example.books.util;

public enum Route {
    LOGIN,SIGNUP,WELCOME,USER,SIDEPANEL,ADMINLOGIN,ADMINSIGNUP,ADMIN,BOOK,LIBRARYBRANCH,TRANSACTIONMANAGE,TRANSACTIONHISTORY,MYBOOKS,BORROWBOOKS,BORROWINGBOOKS
}
